
version: '3.8'

services:
  zbx_map_manager:
    build: .
    container_name: zbx_map_manager
    networks:
      - app-network
    restart: always
    volumes:
      - .:/app
    ports:
      - "8065:8065"
    environment:
      - PYTHONPATH=/app
      - TZ=Europe/Moscow
    command: python map_manager/core/main.py

networks:
  app-network:
    driver: bridge





