
version: '3.8'

services:
  ext_jober_cron:
    build:
      context: .
      dockerfile: externaljober/cron/Dockerfile
    container_name: jober_cron
    environment:
      - TZ=Europe/Moscow
    networks:
      - app-network
    ports:
      - "8011:8011"
    restart: always

  ext_jober_worker:
    build:
      context: .
      dockerfile: externaljober/worker/Dockerfile
    container_name: jober_worker
    environment:
      - TZ=Europe/Moscow
    networks:
      - app-network
    ports:
      - "8012:8012"
    restart: always


networks:
  app-network:
    driver: bridge
